# Generated by Django 2.1.5 on 2019-01-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crawlapp.Url'),
        ),
    ]
