# Generated by Django 2.1.5 on 2019-01-12 06:51

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crawlapp', '0002_auto_20190112_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.Empty, related_name='children', to='crawlapp.Url'),
        ),
    ]
